/**
 * Press Brake Simulator — shared domain types (THE CONTRACT).
 *
 * Every module imports from here. Do not edit this file inside a module task;
 * report contract problems in your result instead so the integrator resolves them.
 *
 * Units: millimetres, degrees, kN (force), MPa (stress), seconds. Angles in degrees
 * unless a name ends in `Rad`.
 *
 * ── Coordinate frames ────────────────────────────────────────────────────────
 * FLAT frame (2D, u/v): the flat-pattern plane as drawn in the DXF. The sheet's
 *   "top" face normal is +w (right-handed u,v,w). Bend direction 'up' rotates the
 *   child flange toward +w, 'down' toward -w.
 *
 * PART frame (3D, x/y/z): the folded part. Root flange lies in the plane w=0 with
 *   u→x, v→y, w→z. Bends fold subtrees out of this plane.
 *
 * MACHINE frame (3D): origin at the centre of the die V, on the die shoulder plane
 *   (die top surface), at the LEFT end of the bed (operator's left).
 *     +X → toward the BACK of the machine (backgauge side). Operator stands at -X.
 *     +Y → up (ram moves along -Y to bend).
 *     +Z → along the bed, left→right as the operator sees it. Bend lines lie along Z.
 *   Backgauge X = distance from the bend line to the finger stop face (+X).
 *   Backgauge R = finger height (0 = finger top flush with die shoulder plane).
 *
 * TOOL profile frames (2D cross-sections in the machine XY plane, extruded along Z):
 *   Punch : origin at the TIP point; +Y up toward the ram clamp; +X toward machine back.
 *   Die   : origin at the V CENTRE on the shoulder plane (top surface); +Y up.
 *   Finger: origin at the bottom of the STOP FACE (the face the sheet touches, at X=0);
 *           the finger body extends toward +X (behind the stop face); +Y up.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Primitives
// ─────────────────────────────────────────────────────────────────────────────

export interface Vec2 { x: number; y: number }
export interface Vec3 { x: number; y: number; z: number }

/** Closed polygon, implicit closing edge, no self-intersections. Winding is not assumed. */
export type Polygon2 = Vec2[];

/** A planar closed polygon in 3D (all points coplanar). */
export type Polygon3 = Vec3[];

/** 4x4 column-major transform (same layout as three.js Matrix4.elements). */
export type Mat4 = number[];

export type BendDirection = 'up' | 'down';

export type Language = 'en' | 'th';

// ─────────────────────────────────────────────────────────────────────────────
// Material
// ─────────────────────────────────────────────────────────────────────────────

export interface Material {
  id: string;                 // 'mild-steel' | 'stainless-304' | 'aluminium-5052' | custom
  name: string;
  tensileStrength: number;    // MPa (Rm), used for tonnage
  kFactor: number;            // default k-factor for BA (0.33–0.5)
  /** Springback in degrees at ri/t ≈ 1 for a 90° air bend; scaled by planner. */
  springbackDeg: number;
  /** Minimum inner radius as a multiple of thickness (cracking limit). */
  minInnerRadiusFactor: number;
  density?: number;           // kg/m³ (optional, for part mass)
}

// ─────────────────────────────────────────────────────────────────────────────
// Flat pattern & bends
// ─────────────────────────────────────────────────────────────────────────────

export interface BendLine {
  id: string;
  /** End points in FLAT frame (u,v). The line is the CENTRE of the bend zone. */
  p0: Vec2;
  p1: Vec2;
  direction: BendDirection;
  /** Rotation from flat, 0 < angle < 180. 90 = right-angle bend. 135 = 45° included (acute). */
  angle: number;
  innerRadius: number;        // ri, mm
  kFactor: number;            // used for bend allowance of this bend
  /** Where the value came from — drives UI badges and confidence. */
  source: 'dxf' | 'step' | 'mesh' | 'user' | 'default';
}

export interface FlatPattern {
  id: string;
  name: string;
  thickness: number;          // t, mm
  materialId: string;
  /** Outer boundary in FLAT frame. Arcs already flattened to segments (chord tol ≤ 0.05 mm). */
  outline: Polygon2;
  /** Inner boundaries (holes/cutouts). */
  holes: Polygon2[];
  bends: BendLine[];
  /** Original units in the source file, for the UI. */
  sourceUnits?: 'mm' | 'in';
  /** Free-form provenance: filename, layers used, etc. */
  provenance?: Record<string, string>;
}

/** A flange = planar region of the flat pattern bounded by outline/bend lines. */
export interface Flange {
  id: string;
  /** Region polygon in FLAT frame (portion of the outline between bend zones). */
  polygon: Polygon2;
  holes: Polygon2[];
  /** ids of bends that touch this flange. */
  bendIds: string[];
}

/** Tree edge: `bendId` connects `parentFlangeId` → `childFlangeId`. */
export interface FlangeLink {
  bendId: string;
  parentFlangeId: string;
  childFlangeId: string;
}

/** Flat pattern + flange tree. Root flange has no parent. */
export interface PartModel {
  flat: FlatPattern;
  flanges: Flange[];
  rootFlangeId: string;
  links: FlangeLink[];
  /** Bend allowance per bend id (mm), computed from angle/ri/k/t. */
  bendAllowance: Record<string, number>;
  /** Bounding box of the flat pattern. */
  flatBounds: { min: Vec2; max: Vec2 };
}

/** 0 = flat, 1 = fully bent, per bend id. Missing bend ⇒ 1 (fully bent). */
export type FoldState = Record<string, number>;

/** Output of the fold kinematics: geometry in PART frame for a given FoldState. */
export interface FoldedGeometry {
  /** One entry per flange: its mid-surface polygon placed in 3D + the sheet normal. */
  flanges: Array<{
    flangeId: string;
    /** Transform FLAT(u,v,0) → PART for this flange (column-major 4x4). */
    transform: Mat4;
    midSurface: Polygon3;      // polygon in PART frame (mid-surface)
    holes: Polygon3[];
    normal: Vec3;              // +w direction of this flange in PART frame
  }>;
  /** One entry per bend: the curved zone, as a sweep of the bend line along an arc. */
  bends: Array<{
    bendId: string;
    /** Current fold angle (deg) = angle * fraction. */
    currentAngle: number;
    /** Arc centre line: axis through `axisPoint` along `axisDir` (unit), PART frame. */
    axisPoint: Vec3;
    axisDir: Vec3;
    /** Radius of the mid-surface arc (ri + t/2) and inner radius. */
    midRadius: number;
    innerRadius: number;
    /** Start edge of the zone (segment on the parent side) and unit direction of curvature. */
    startEdge: [Vec3, Vec3];
    /** Direction from the start edge toward the arc centre (unit, PART frame). */
    toCentre: Vec3;
    /** Direction tangent to the sheet at the start edge, pointing into the zone (unit). */
    tangent: Vec3;
    /** Sheet thickness (copied for convenience). */
    thickness: number;
  }>;
  /** Bounding box in PART frame including thickness. */
  bounds: { min: Vec3; max: Vec3 };
}

// ─────────────────────────────────────────────────────────────────────────────
// Tooling
// ─────────────────────────────────────────────────────────────────────────────

export interface ToolProfile {
  /** Closed cross-section polygon in the tool's local frame (see header). */
  points: Polygon2;
}

export type ToolSource = 'standard' | 'custom';

export interface ToolBase {
  id: string;
  name: string;
  source: ToolSource;
  /** Height from the frame origin to the clamping reference (mm). */
  height: number;
  /** Max load per metre, kN/m. */
  maxLoadPerMeter: number;
  /** Available segment lengths (mm). Empty ⇒ a single full-length tool = machine bed. */
  segmentLengths: number[];
  profile: ToolProfile;
  notes?: string;
}

export type PunchFamily = 'straight' | 'gooseneck' | 'acute' | 'radius' | 'hemming' | 'custom';

export interface Punch extends ToolBase {
  kind: 'punch';
  family: PunchFamily;
  tipRadius: number;          // mm
  tipAngle: number;           // included angle at the tip, deg (e.g. 88, 30)
  /** Width of the body in X (mm) — for quick capacity display. */
  bodyWidth: number;
}

export type DieFamily = 'v' | 'multi-v' | 'hemming' | 'u' | 'custom';

export interface Die extends ToolBase {
  kind: 'die';
  family: DieFamily;
  vWidth: number;             // V opening at the shoulder plane, mm (active V)
  vAngle: number;             // included V angle, deg (e.g. 88, 85, 30)
  shoulderRadius: number;     // mm
  /** Total width in X (mm). */
  bodyWidth: number;
}

export interface Finger extends ToolBase {
  kind: 'finger';
  /** Height of the vertical stop face (mm). */
  stopHeight: number;
  /** Depth of the finger body behind the stop face (mm, +X). */
  bodyDepth: number;
  /** Finger width along Z (mm). */
  width: number;
}

export type Tool = Punch | Die | Finger;

export interface ToolLibrary {
  punches: Punch[];
  dies: Die[];
  fingers: Finger[];
  materials: Material[];
  machines: Machine[];
  /** Schema version for persistence migrations. */
  version: 1;
}

// ─────────────────────────────────────────────────────────────────────────────
// Machine
// ─────────────────────────────────────────────────────────────────────────────

export interface Machine {
  id: string;
  name: string;
  bedLength: number;          // Z extent, mm
  capacity: number;           // kN (e.g. 1000 kN = ~100 t)
  stroke: number;             // Y travel of the ram, mm
  /** Open height: die shoulder plane → ram clamp bottom face at top-dead-centre, mm.
   *  (Daylight with tools = daylight - punchHeight - dieHeight.) */
  daylight: number;
  /** Distance from the bend line back to the side-frame throat (X), mm. */
  throatDepth: number;
  /** Clear distance between side frames (Z), mm. Usually ≥ bedLength. */
  distanceBetweenFrames: number;
  ram: {
    /** Ram/upper beam thickness in X (mm), centred on the bend line. */
    thickness: number;
    /** Height of the beam above the tool clamp (mm) — collision volume. */
    height: number;
    /** Clamp/holder block below the beam: X thickness and Y height. */
    clampThickness: number;
    clampHeight: number;
    /** Speeds mm/s for animation. */
    speeds: { approach: number; bend: number; retract: number };
  };
  table: {
    /** Table/bed X width (mm), centred on the bend line. */
    width: number;
    /** Die holder: X width and Y height (below the die). */
    holderWidth: number;
    holderHeight: number;
    /** Height of the bed block below the holder (collision volume). */
    height: number;
  };
  backgauge: {
    xMin: number; xMax: number; // finger stop-face travel from bend line, mm
    rMin: number; rMax: number; // finger height range, mm (0 = flush with die top)
    zMin: number; zMax: number; // finger travel along the bed, mm
    fingerCount: number;
    fingerId: string;           // Finger tool used
    /** Backgauge beam behind the fingers: X depth from finger stop face + bodyDepth. */
    beamDepth: number;
    beamHeight: number;
    speed: number;              // mm/s
  };
  /** Per-tool Y-axis correction to apply to computed ram depth (calibration), mm. */
  yCorrection: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Tool setup (what is mounted on the machine)
// ─────────────────────────────────────────────────────────────────────────────

export interface ToolStation {
  id: string;
  punchId: string;
  dieId: string;
  /** Z range on the bed occupied by this station (mm). */
  zStart: number;
  zEnd: number;
  /** Punch mounted reversed (profile mirrored in X, e.g. gooseneck relief to the front). */
  punchFlipped: boolean;
  dieFlipped: boolean;
}

export interface ToolSetup {
  machineId: string;
  stations: ToolStation[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Bend program (planner output) and simulation
// ─────────────────────────────────────────────────────────────────────────────

/**
 * How the part is placed for a bend step. The part is positioned so that the
 * bend line lies along machine Z at X=0, the sheet rests on the die shoulder plane,
 * and the GAUGED side (toward +X, the backgauge) is `gaugedFlangeId`.
 */
export interface Placement {
  bendId: string;
  /** Flange that lies toward the backgauge (+X) and touches the fingers. */
  gaugedFlangeId: string;
  /** Flange on the operator side (-X). */
  frontFlangeId: string;
  /** Part turned over (which sheet face is up). false = flat-pattern +w faces up. */
  flipped: boolean;
  /** Transform PART → MACHINE for the part BEFORE this bend (all previous bends applied). */
  transform: Mat4;
  /** Z offset of the part so it sits within the chosen station. */
  stationId: string;
}

export interface CollisionReport {
  /** What collided with the part. */
  with: 'punch' | 'ram' | 'clamp' | 'die' | 'holder' | 'table' | 'finger' | 'backgauge-beam' | 'frame' | 'self';
  /** Fold fraction of the current bend at which it happens (0 = at placement, 1 = at target). */
  atFraction: number;
  /** Approximate location in MACHINE frame. */
  location: Vec3;
  /** Penetration depth estimate, mm. */
  depth: number;
  severity: 'error' | 'warning';
  messageKey: string;         // i18n key
}

export interface BendStep {
  index: number;
  bendId: string;
  stationId: string;
  placement: Placement;
  /** Target angle (deg from flat) and the angle to bend to including springback. */
  targetAngle: number;
  overbendAngle: number;
  springback: number;
  /** Ram depth below die shoulder plane at overbendAngle (mm, positive = below). */
  ramDepth: number;
  /** Required force for this bend (kN) and per metre (kN/m). */
  force: number;
  forcePerMeter: number;
  /** Bend line length (mm). */
  bendLength: number;
  /** Backgauge settings. */
  backgauge: { x: number; r: number; z: number[] } | null;
  /** Length of the gauged flange from the bend line to the stop face (mm). */
  gaugedFlangeLength: number;
  /** Part manipulation relative to the previous step. */
  manipulation: { flip: boolean; rotate180: boolean; stationChange: boolean };
  collisions: CollisionReport[];
  /** i18n keys for advisory notes (short flange, tonnage near limit, etc). */
  warnings: string[];
}

export interface BendProgram {
  partId: string;
  partName: string;
  machineId: string;
  setup: ToolSetup;
  materialId: string;
  thickness: number;
  steps: BendStep[];
  /** Max force across steps (kN), vs machine capacity. */
  maxForce: number;
  feasible: boolean;
  warnings: string[];
  /** Search statistics for the UI. */
  stats: { sequencesEvaluated: number; timeMs: number };
}

/** Pure description of the sequence search options. */
export interface PlannerOptions {
  /** Fold sampling for collision sweeps (deg). */
  sweepStepDeg: number;
  /** Max sequences to evaluate before falling back to greedy. */
  maxSequences: number;
  /** Cost weights. */
  weights: { flip: number; rotate: number; stationChange: number; shortFlange: number; collisionWarning: number };
  /** Minimum gauged flange length as a multiple of V width (default 0.7). */
  minFlangeFactor: number;
  /** Fixed order provided by the user (bend ids) — planner only computes placements. */
  fixedOrder?: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Simulation timeline
// ─────────────────────────────────────────────────────────────────────────────

export type SimPhase = 'position' | 'gauge' | 'approach' | 'bend' | 'release' | 'retract' | 'reposition';

export interface SimKeyframe {
  stepIndex: number;
  phase: SimPhase;
  /** 0..1 within the phase. */
  t: number;
  /** Ram Y position (clamp bottom) in MACHINE frame. */
  ramY: number;
  /** Fold state of the whole part at this instant. */
  foldState: FoldState;
  /** Transform PART → MACHINE at this instant. */
  partTransform: Mat4;
  backgauge: { x: number; r: number; z: number[] } | null;
  /** Collisions active at this instant (for highlighting). */
  collisions: CollisionReport[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Import results
// ─────────────────────────────────────────────────────────────────────────────

/** Triangle soup with optional B-rep face grouping (STEP) — the mesh importers' output. */
export interface TriangleMesh {
  positions: Float32Array;    // xyz triplets
  indices: Uint32Array;       // triangle index triplets
  normals?: Float32Array;     // per-vertex, optional
  /** For STEP: triangle ranges per B-rep face [first, last] inclusive (triangle indices). */
  faceGroups?: Array<{ first: number; last: number }>;
  units: 'mm';
  name: string;
}

/** Sheet-metal feature recognition result. */
export interface RecognizedSheet {
  thickness: number;
  bendCount: number;
  /** Detected bends in PART frame (3D) — before unfolding. */
  bends3d: Array<{
    id: string;
    axisPoint: Vec3;
    axisDir: Vec3;
    innerRadius: number;
    angle: number;              // deg from flat
    length: number;             // along the axis, mm
    /** Ids of the two planar faces (flanges) joined by this bend. */
    faceA: string;
    faceB: string;
  }>;
  /** Planar faces of ONE side of the sheet (the reference side), with outline in 3D. */
  faces: Array<{ id: string; normal: Vec3; origin: Vec3; outline: Polygon3; holes: Polygon3[] }>;
  /** The unfolded flat pattern derived from the faces + bends. */
  flat: FlatPattern;
  /** Confidence 0..1 and human-readable issues (i18n keys). */
  confidence: number;
  issues: string[];
}

export interface ImportResult {
  flat?: FlatPattern;
  mesh?: TriangleMesh;
  recognized?: RecognizedSheet;
  /** i18n keys of problems that did not prevent import. */
  warnings: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Project (what the UI saves/loads)
// ─────────────────────────────────────────────────────────────────────────────

export interface Project {
  version: 1;
  name: string;
  part: PartModel | null;
  setup: ToolSetup;
  machineId: string;
  materialId: string;
  plannerOptions: PlannerOptions;
  program: BendProgram | null;
  language: Language;
}
